const Themes = {
  christmasSongs : ['','Silent Night', 'Frosty the Snowman', 'Santa claus is coming to town', 'O Holy Night', 'Last Christmas', 'Santa Baby', 'White Christmas', 'Let it Snow', 'Blue Christmas', 'Carols of the Bells', 'Sleigh Ride', 'Deck the Halls', 'O come all ye faithful', 'Do you hear what I hear', 'Winter Wonderland', 'We Wish You A Merry Christmas', 'Ill be home for christmas', 'Its beginning to look a lot like christmas', 'I saw mommy kissing santa claus', 'Baby its cold outside', 'Theres no place like home', 'Silver Bells', 'this Christmas', 'Holly Jolly christmas', 'grandma got run over by a reindeer', 'Angels we have heard on high'],
  elf: ['','syrup spagetti', 'worlds best coffee', 'santa', 'angry elf', 'son of a nutcracker', 'i am in a store and singing', 'theres no singng in the north pole', 'cotton headed ninny-muggins', 'buddy', 'leon the snowman', 'papa elf', 'buddy', 'north pole', 'new york city', 'yellow snow', 'Im in love and dont care who knows it', 'snowball fight', 'candy, candy canes, candy corn, and syrup', 'you do not smell like santa', ],
  christmasRandom: ['','angel', 'baby jesus', 'stocking', 'reindeer', 'santas list', 'gingerbread house', 'christmas lights','snowman', 'snowflake', 'christmas tree', 'elf', 'three wise men','presents under the tree', 'ornaments', 'sleigh','carolers', 'snowball fight', 'icicle', 'christmas eve', 'santas workshop', 'the north pole', 'toys', 'little drummer boy', 'chimney', 'mrs. claus', 'christmas lights', 'snowball fight', 'ice skating', 'wrapping paper', 'mittens', 'sledding'],
  christmasFood: ['','candy canes', 'cinnamon rolls', 'banana bread pudding', 'hot chocolate', 'chocolate oranges', 'ginger bread man', 'fruit cake', 'ham', 'turkey', 'gingerbread', 'eggnog','gumdrops', 'cookies', 'fudge', 'stuffing', 'apple cider', 'apple pie', 'biscuits', 'mashed potatos', 'prime rib'],
  family: ['','jordyn', 'tyler', 'mimi', 'stacey', 'shawn', 'ryan m.', 'ryan e.', 'chelsey', 'cash', 'kenzi', 'scarlett', 'sophie', 'audrey', 'ireland'],
  //christmasCharacters: ['grinch', 'santa claus', 'rudolph', 'buddy the elf', 'mrs claus', 'jack frost', 'jack skellington', 'father time', 'frosty the snowman', '' ]
}

export default Themes